# Generated by Django 6.0.4 on 2026-07-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_otpverification_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('restock', 'Restock'), ('manual', 'Manual')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('before_stock', models.PositiveIntegerField()),
                ('after_stock', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='main.order')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='main.productsize')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
