# Generated by Django 6.0.4 on 2026-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_paymentaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='waiting', max_length=20),
        ),
    ]
