# Generated by Django 6.0.4 on 2026-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
