# Generated by Django 6.0.4 on 2026-07-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
