# Generated by Django 6.0.4 on 2026-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='page_type',
            field=models.CharField(choices=[('product', 'Product'), ('branch', 'Branch'), ('career', 'Career')], default='product', max_length=20),
        ),
    ]
