# Generated by Django 6.0.4 on 2026-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(default='uz', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='orders_per_page',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_per_page',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', max_length=100),
        ),
    ]
