# Generated by Django 6.0.4 on 2026-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesettings_dashboard_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© Dunyo Textile. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('en', 'English'), ('ru', 'Russian')], default='uz', max_length=20),
        ),
    ]
